package utils

const (
	SERVERITY_LOW         = "LOW"
	SERVERITY_MEDIUM      = "MEDIUM"
	SERVERITY_HIGH        = "HIGH"
	SERVERITY_CRITICAL    = "CRITICAL"
	SERVERITY_UNSPECIFIED = "UNSPECIFIED"

	VULNERABILITY_SEVERITY = "Severity"
	VULNERABILITY_PACKAGE  = "Package"

	POLICY_PACKAGE_ACTIONS_DENY = "DENY"
	POLICY_PACKAGE_ACTIONS_ALLOW = "ALLOW"
)
